sudo: false
language: python
matrix:
  include:
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  allow_failures:
  - python: 3.5
    env: TOXENV=py35
install: pip install tox
cache: pip
script: tox
notifications:
  email: false
